# Homebrew formula for ctx — installed from prebuilt release binaries.
#
# Tap repository layout:
#   <tap>/
#     Formula/
#       ctx.rb            <- this file
#
# Usage:
#   brew tap halloffame12/CTX
#   brew install ctx
#
# Generated by scripts/update-homebrew.sh — do not edit by hand.
class Ctx < Formula
  desc "Codebase intelligence and context engine for AI coding agents"
  homepage "https://github.com/halloffame12/CTX"
  version "0.1.2"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.2/ctx-macos-aarch64"
    sha256 "24f81af4dcdd63b31ed58fefa5a79e08a560aed437a3a5353a9de1193e3266ed"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.2/ctx-macos-x86_64"
    sha256 "fa82877423814c3e275b26f5cb06127efd63fe527d278b5762a233ffda5b7565"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.2/ctx-linux-aarch64"
    sha256 "3b64775a1d678175adb263bc876948a5bd3333002e263602efb2d0b13998f8de"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/halloffame12/CTX/releases/download/v0.1.2/ctx-linux-x86_64"
    sha256 "d38b88d385be8d8fe91fee172b3b68e94699f6bb1e1f4723fcbd1c55bb759d99"
  else
    odie "ctx: unsupported platform — only macOS (Intel/ARM) and Linux (Intel/ARM) are supported"
  end

  def install
    bin.install Dir["ctx-*"].first => "ctx"
  end

  test do
    assert_match "ctx #{version}", shell_output("#{bin}/ctx --version")
  end
end
