// @generated by thrift-compiler 1.4. DO NOT EDIT.
pub struct GeneratedStruct {
    pub id: i64,
    pub name: String,
}

pub fn decode_generated(data: &[u8]) -> GeneratedStruct {
    let id = read_i64(data);
    let name = read_string(data);
    GeneratedStruct { id, name }
}
