// Code generated by protoc-gen-go. DO NOT EDIT.
package api

type GeneratedMessage struct {
	Id   int64  `json:"id"`
	Name string `json:"name"`
}

func (m *GeneratedMessage) Reset() {}

func (m *GeneratedMessage) String() string {
	return m.Name
}
