# Generated by codegen. DO NOT EDIT.
import marshmallow

class ApiResponseSchema(Schema):
    id = fields.Int()
    name = fields.Str()

def parse_response(data: str) -> dict:
    return json.loads(data)
