#!/usr/bin/env bash
# Regenerate packaging/homebrew/tap/Formula/ctx.rb with the current version
# and real sha256 hashes from dist/checksums.txt.
#
# Usage: scripts/update-homebrew.sh
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FORMULA="$ROOT/packaging/homebrew/tap/Formula/ctx.rb"
VERSION="$(grep '^version' "$ROOT/Cargo.toml" | head -1 | sed -E 's/version *= *"([^"]+)"/\1/')"

# read sha for an artifact from dist/checksums.txt (hash  file)
sha() { grep -m1 "  $1$" "$ROOT/dist/checksums.txt" | awk '{print $1}'; }

cat > "$FORMULA" <<EOF
# Homebrew formula for ctx — installed from prebuilt release binaries.
#
# Tap repository layout:
#   <tap>/
#     Formula/
#       ctx.rb            <- this file
#
# Usage:
#   brew tap halloffame12/CTX
#   brew install ctx
#
# Generated by scripts/update-homebrew.sh — do not edit by hand.
class Ctx < Formula
  desc "Codebase intelligence and context engine for AI coding agents"
  homepage "https://github.com/halloffame12/CTX"
  version "$VERSION"

  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/halloffame12/CTX/releases/download/v${VERSION}/ctx-macos-aarch64"
    sha256 "$(sha ctx-macos-aarch64)"
  elsif OS.mac? && Hardware::CPU.intel?
    url "https://github.com/halloffame12/CTX/releases/download/v${VERSION}/ctx-macos-x86_64"
    sha256 "$(sha ctx-macos-x86_64)"
  elsif OS.linux? && Hardware::CPU.arm?
    url "https://github.com/halloffame12/CTX/releases/download/v${VERSION}/ctx-linux-aarch64"
    sha256 "$(sha ctx-linux-aarch64)"
  elsif OS.linux? && Hardware::CPU.intel?
    url "https://github.com/halloffame12/CTX/releases/download/v${VERSION}/ctx-linux-x86_64"
    sha256 "$(sha ctx-linux-x86_64)"
  else
    odie "ctx: unsupported platform — only macOS (Intel/ARM) and Linux (Intel/ARM) are supported"
  end

  def install
    bin.install Dir["ctx-*"].first => "ctx"
  end

  test do
    assert_match "ctx #{version}", shell_output("#{bin}/ctx --version")
  end
end
EOF

echo "updated $FORMULA for v${VERSION}"