/* eslint-disable */
// This file was generated by proto-gen v3.2.0. DO NOT EDIT.
export interface GeneratedThing {
  id: number;
  name: string;
  tags: string[];
}
export function deserializeGeneratedThing(data: string): GeneratedThing {
  const obj = JSON.parse(data);
  return { id: obj.id, name: obj.name, tags: obj.tags };
}
